### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by mohammadnaseri0** [GarudaID/Mod-CODM#3]
Recently, anti-cheat Ban will give you 20 minutes and 1 day to hack Global Can you help with the bypass!?

**Comment by GarudaID** [comment]
> Recently, anti-cheat Ban will give you 20 minutes and 1 day to hack Global Can you help with the bypass!?

hi thank for report.

Tomorrow I will update bypass for Global.
For premium Key u must buy no ban all safe.
30/1 month : 30$ 

email: support@dixies.site
